TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.2
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  holonomic_robot: true
  yaw_goal_tolerance: 6.2
  xy_goal_tolerance: 0.3
