# Define the positions of the wireless repeaters

# Including the model of the wireless repeaters
include "model/beacon_sender_model.inc"

#Load wireless beacons in the map
beacon(
	name "beacon0"
	pose [-12.17 0.4 0.6 90]
)

#Load wireless beacons in the map
beacon(
	name "beacon1"
	pose [5.41 -4.75 0.6 0]
)

#Load wireless beacons in the map
beacon(
	name "beacon2"
	pose [1.22 0.85 0.6 45]
)

#Load wireless beacons in the map
beacon(
	name "beacon3"
	pose [8.24 8.72 0.6 45]
)

#Load wireless beacons in the map
beacon(
	name "beacon4"
	pose [-5.71 -9.07 0.6 45]
)
